source 'https://github.com/yanshiyu/MySpecs.git'
use_frameworks!

platform :ios, '9.0'

target 'YSYCategoryKit_Example' do
  pod 'YSYCategoryKit'

  target 'YSYCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
